jenkins:
  nodes:
  - permanent:
      name: Project-4-Awesome-1
      nodeProperties:
      - authorizationMatrix:
          inheritanceStrategy: inheritingGlobal
          permissions:
          - USER:Agent/Build:Project-4-Awesome-sa-build-1
          - USER:Agent/Connect:hello-world.admin@example.org
          - USER:Agent/Build:hello-world.admin@example.org
          - USER:Agent/Configure:hello-world.admin@example.org
          - USER:Agent/Disconnect:hello-world.admin@example.org
  - permanent:
      name: Project-4-Awesome-2
      nodeProperties:
      - authorizationMatrix:
          inheritanceStrategy: inheritingGlobal
          permissions:
          - USER:Agent/Build:Project-4-Awesome-sa-build-1
          - USER:Agent/Connect:hello-world.admin@example.org
          - USER:Agent/Build:hello-world.admin@example.org
          - USER:Agent/Configure:hello-world.admin@example.org
          - USER:Agent/Disconnect:hello-world.admin@example.org
  securityRealm:
    local:
      users:
      - id: hello-world.admin@example.org
        name: hello-world.admin@example.org
        password: ${PROJECT_4_AWESOME_PASSWD}
        properties:
        - mailer:
            emailAddress: hello-world.admin@example.org
      - id: Project-4-Awesome-sa-build-1
        name: Project-4-Awesome-sa-build-1
jobs:
- script: folder('Project 4 Awesome')
